### ISSUE TITLE
8080 & 8081 port conflicts with tr1d1um and talaria

### ISSUE THREAD

**Issue by fchan2** [Comcast/tr1d1um#32]
When starting the tr1d1um service after talaria is in service, there is a an error message in the tr1d1um.log that indicates the following:

`ts=2017-11-29T16:58:30.035982038Z caller=tr1d1um.go:89 level=info configurationFile=/etc/tr1d1um/tr1d1um.json

ts=2017-11-29T16:58:30.036595832Z caller=sns.go:144 level=debug selfURL=https://:8080/api/v2/aws/sns/1511974710 protocol=https

ts=2017-11-29T16:58:30.036637725Z caller=sns_handler.go:95 level=debug msg="handler not nil" urlPath=/api/v2/aws/sns/1511974710

ts=2017-11-29T16:58:30.036682361Z caller=webpa.go:235 level=info msg="starting server" name=tr1d1um.health address=:8081

ts=2017-11-29T16:58:30.036694028Z caller=health.go:118 level=debug msg="Health Monitor Started"
ts=2017-11-29T16:58:30.036712033Z caller=webpa.go:249 level=info msg="starting server" name=tr1d1um address=:8080

ts=2017-11-29T16:58:30.036807806Z caller=webpa.go:51 level=error error="listen tcp :8080: bind: address already in use"

ts=2017-11-29T16:58:30.036847589Z caller=sns_handler.go:116 level=debug subscribeParams="{\n  Endpoint: \"https://:8080/api/v2/aws/sns/1511974710\",\n  Protocol: \"https\",\n  TopicArn: \"arn:aws:sns:us-east-1:999999999999:fake\"\n}"

ts=2017-11-29T16:58:30.037322711Z caller=webpa.go:51 level=error error="listen tcp :8081: bind: address already in use"`

tr1d1um is configured to use port 8095 and talaria uses port 8080. Need to understand why tr1d1um is still listening on port 8080 after restarting services. Please see attachments for config and logs.

**Comment by fchan2** [comment]
[tr1d1um.zip](https://github.com/Comcast/tr1d1um/files/1515983/tr1d1um.zip)

**Comment by joe94** [comment]
Thanks @fchan2 for reporting this. This probably has to do with the default port used by our metrics https://github.com/Comcast/tr1d1um/blob/master/src/tr1d1um/tr1d1um.go#L58. 

We have decided not to go in the current route with the metrics so I will be reverting these.

**Comment by schmidtw** [comment]
@fchan2 we reverted the metrics feature until we can make it more configurable/optional.  Try the next release (0.1.1-131) & the conflict should be gone.

**Comment by fchan2** [comment]
I upgraded to 0.1.1-131, but I still see the port conflict. Here is what I did -- maybe I missed something?

```
# service tr1d1um stop
# rpm --import https://github.com/Comcast/tr1d1um/releases/download/0.1.1-131/RPM-GPG-KEY-comcast-webpa
# yum install https://github.com/Comcast/tr1d1um/releases/download/0.1.1-131/tr1d1um-0.1.1-131.el6.x86_64.rpm
# service tr1d1um start
```
