### ISSUE TITLE
curl to tr1d1um URL returns 404 Not Found error

### ISSUE THREAD

**Issue by fchan2** [Comcast/tr1d1um#36]
We have scytale, talaria, and tr1d1um running on a single machine with the three services currently listening:

> tcp 0 0 :::8096 :::* LISTEN 4180/tr1d1um
tcp 0 0 :::8080 :::* LISTEN 4157/talaria
tcp 0 0 :::6000 :::* LISTEN 4136/scytale
tcp 0 0 :::8081 :::* LISTEN 4157/talaria
tcp 0 0 :::6001 :::* LISTEN 4136/scytale
tcp 0 0 :::6002 :::* LISTEN 4136/scytale
tcp 0 0 :::8095 :::* LISTEN 4180/tr1d1um

If a curl command is sent to retrieve TR-181 parameters using this command

`curl -i http://10.11.160.49:8095/api/v2/device/mac:f8a097ea7206/config?names=Device.DeviceInfo.SerialNumber`

The following is displayed:

> HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Tue, 05 Dec 2017 17:36:41 GMT
Content-Length: 19
404 page not found

**Comment by joe94** [comment]
That command should be supported. What do the logs say?

**Comment by fchan2** [comment]
I checked tr1d1um.log and there do not appear to be any log messages pertaining to the output of that command. However, I do see these messages in the logs:

`
ts=2017-12-06T22:00:55.387003231Z caller=sns_handler.go:135 level=error msg="SNS subscribe error" attempt=12 error="InvalidClientTokenId: The security token included in the request is invalid.\n\tstatus code: 403, request id: 93fa5c69-871c-58c9-b373-0ecbedcb0699"`

Also, I added the targetURL of my scytale in the tr1d1um.json:

        "primary": {
            "address": ":8095"
        },

        "health": {
            "address": ":8096",
            "logInterval": "61s",
            "options": [
                "PayloadsOverZero",
                "PayloadsOverHundred",
                "PayloadsOverThousand",
                "PayloadsOverTenThousand"
            ]
        },

        "targetURL": ["http://localhost:6000/api/v2/device/send"],

**Comment by joe94** [comment]
This is the correct format for targetURL:
`"targetURL": "http://localhost:6000"`

**Comment by fchan2** [comment]
I set the targetURL to scytale as shown, but still get the 404 error when I try the curl command above.


{
        "primary": {
            "address": ":8095"
        },

        "health": {
            "address": ":8096",
            "logInterval": "61s",
            "options": [
                "PayloadsOverZero",
                "PayloadsOverHundred",
                "PayloadsOverThousand",
                "PayloadsOverTenThousand"
            ]
        },

        "targetURL": "http://localhost:6000",

        "log" : {
                "file"      : "/var/log/tr1d1um/tr1d1um.log",
                "level"     : "DEBUG",
                "maxSize"   : 5242880,
                "maxBackup" : 3
        },


        "aws": {
               "accessKey": "fake",
               "secretKey": "fake",
               "env": "fake",
               "sns": {
                      "region": "us-east-1",
                      "topicArn": "arn:aws:sns:us-east-1:999999999999:fake",
                      "urlPath" : "/api/v2/aws/sns"
               }
        }

}

**Comment by joe94** [comment]
Keep in mind that if the device with info `mac:f8a097ea7206` is not connected to talaria, you will get a 404 statusCode. So, be sure that you see such device in the list you get by hitting `http://localhost:[talaria-bind-address]/api/v2/devices`

**Comment by fchan2** [comment]
Yes, I have verified that this device is connected to talaria.

`
{"devices":[{"id": "mac:f8a097ea7206", "pending": 0, "statistics": {"bytesSent": 21, "messagesSent": 1, "bytesReceived": 0, "messagesReceived": 0, "duplications": 0, "connectedAt": "2017-12-06T23:05:48.783864473Z", "upTime": "31m55.444525679s"}},{"id": "mac:0036764163a5", "pending": 0, "statistics": {"bytesSent": 21, "messagesSent": 1, "bytesReceived": 0, "messagesReceived": 0, "duplications": 0, "connectedAt": "2017-12-06T23:05:46.000130027Z", "upTime": "31m58.228293867s"}}]}`

**Comment by joe94** [comment]
That's weird. 
A few things to try in case you havent' (ordered from the most to least relevant)

1. Look at the logs from each machine to see if you can catch any errors.

2. Double check your config files. Here are some samples for each machine:
`scytale`: https://github.com/Comcast/scytale/blob/master/etc/scytale/scytale.json
`talaria`:  https://github.com/Comcast/talaria/blob/master/src/talaria/talaria.json
`tr1d1um` (work in progress but might still be useful): https://github.com/Comcast/tr1d1um/pull/34/files

3. Remember that `tr1d1um` talks to `scytale` which it in turn talks to `talaria`. 
It might help to know that tr1d1um builds the path `[targetURL]/api/v2/device` to talk to scytale. 

4. Update your machine versions. There are a few improvements in the latest machines that will help with debugging (using header values in the response)

**Comment by joe94** [comment]
I think I found the issue. You are missing the "version" value in your config file like follows below. A default value should have been there.


```
"targetURL": "http://localhost:6000",
"version": "v2"
```

**Comment by fchan2** [comment]
Thanks for the updated parameter. I guess I must have an old JSON from when I first did the installation.

I am now seeing a 403 Forbidden error:

`{"message": "missing header: Authorization"}`

I know that that the `-H Authorization: <header>` needs to be present in the `curl` command, but not sure what the header should be. This is a local installation, so no SAT tokens are required (I think). Any ideas where to go from here?

**Comment by fchan2** [comment]
@joe94 we can probably close this issue since the issue on tr1d1um is resolved. The issue in the last post can be opened against scytale since it is authorization related.

**Comment by joe94** [comment]
@fchan2 Yeah, I'm gonna close this issue but that 403 authentication error is expected. 

Please update your tr1d1um machine to the latest version. Then, in your config file, fill out the value for `authHeader` with a base64 encoded basic auth key `[basicAuth]` which then you pass as the header value for key `Authorization` as `Basic [basicAuth]`. If you're familiar with basic auth, this will be piece of cake. 

Your updated config file should look something like this:

```
...

"targetURL": "blah",
"authHeader": "[basic auth key]",

...
```
